### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sylestiel** [vanheeringen-lab/anansnake#10]
Hello!

Is it absolutely essential to use mamba for this purpose?

I was trying to incorporate anansnake to run scANANSE but ran into the following error:

Error in rule maelstrom:
    jobid: 40
    input: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/Peak_Counts.tsv, /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/mm10.gimme.vertebrate.v5.0.pfm, /Users/pediatrics/Desktop/R_projects/scANANSE/data/mm10
    output: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/mm10-maelstrom
    log: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/log_mm10_maelstrom.txt (check log file(s) for error message)
    conda-env: /Users/pediatrics/.snakemake/conda/52b8cb6f4a78ac804c0afe54b1ecb2c2_

RuleException:
CalledProcessError in line 80 of /Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/gimme.smk:
Command 'source /Users/pediatrics/anaconda3/envs/anansnake/bin/activate '/Users/pediatrics/.snakemake/conda/52b8cb6f4a78ac804c0afe54b1ecb2c2_'; set -euo pipefail;  python /Users/pediatrics/.snakemake/scripts/tmpj_rlppgz.maelstrom.py' returned non-zero exit status 1.
  File "/Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/gimme.smk", line 80, in __rule_maelstrom
  File "/Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-23T152751.937220.snakemake.log

Can you help me understand where the problem lies?

Thank you!

**Comment by JGASmits** [comment]
Hi Sylestiel,

Mamba is faster than conda when installing.  
Am i correct in assuming this an error when you try to run anansanke? Or do you earlier get a error during the instalation?

What does the error logs: 
"/Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/log_mm10_maelstrom.txt" 
" .snakemake/log/2023-08-23T152751.937220.snakemake.log" 

contain?

Gr Jos

**Comment by sylestiel** [comment]
Thanks!
